# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python library lingvo

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        sudo apt-get install libsndfile1
        python -m pip install --upgrade pip
        pip install flake8 pytest pytype
        pip install -r lingvo/requirements.txt
    - name: Lint with flake8
      run: |
        flake8 publications/*/*/*.py
        flake8 --indent-size 2 --max-line-length 80 lingvo
    - name: Run tests
      run: |
        bash lingvo/run_tests.sh
