# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python library DiarizationLM

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r DiarizationLM/requirements.txt
    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 --indent-size 2 --max-line-length 80 DiarizationLM
    - name: pytype
      run: |
        pip install pytype
        pip install torch
        pip install trl
        pip install "unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git"
        export PYTHONPATH=DiarizationLM:$PYTHONPATH
        pytype DiarizationLM
    - name: Run tests
      run: |
        pip install pytest codecov
        bash DiarizationLM/run_tests.sh
        bash DiarizationLM/run_tools.sh
