# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python library DiarizationLM

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest pytype
        pip install -r DiarizationLM/requirements.txt
    - name: Lint with flake8
      run: |
        flake8 --indent-size 2 --max-line-length 80 DiarizationLM
    - name: pytype
      run: |
        pytype DiarizationLM/*.py
        pytype DiarizationLM/diarizationlm
    - name: Run tests
      run: |
        pip install codecov
        bash DiarizationLM/run_tests.sh
        bash DiarizationLM/run_tools.sh
